require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CreditedOrdersController do

  # This should return the minimal set of attributes required to create a valid
  # CreditedOrder. As you add validations to CreditedOrder, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CreditedOrdersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all credited_orders as @credited_orders" do
      credited_order = CreditedOrder.create! valid_attributes
      get :index, {}, valid_session
      assigns(:credited_orders).should eq([credited_order])
    end
  end

  describe "GET show" do
    it "assigns the requested credited_order as @credited_order" do
      credited_order = CreditedOrder.create! valid_attributes
      get :show, {:id => credited_order.to_param}, valid_session
      assigns(:credited_order).should eq(credited_order)
    end
  end

  describe "GET new" do
    it "assigns a new credited_order as @credited_order" do
      get :new, {}, valid_session
      assigns(:credited_order).should be_a_new(CreditedOrder)
    end
  end

  describe "GET edit" do
    it "assigns the requested credited_order as @credited_order" do
      credited_order = CreditedOrder.create! valid_attributes
      get :edit, {:id => credited_order.to_param}, valid_session
      assigns(:credited_order).should eq(credited_order)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CreditedOrder" do
        expect {
          post :create, {:credited_order => valid_attributes}, valid_session
        }.to change(CreditedOrder, :count).by(1)
      end

      it "assigns a newly created credited_order as @credited_order" do
        post :create, {:credited_order => valid_attributes}, valid_session
        assigns(:credited_order).should be_a(CreditedOrder)
        assigns(:credited_order).should be_persisted
      end

      it "redirects to the created credited_order" do
        post :create, {:credited_order => valid_attributes}, valid_session
        response.should redirect_to(CreditedOrder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved credited_order as @credited_order" do
        # Trigger the behavior that occurs when invalid params are submitted
        CreditedOrder.any_instance.stub(:save).and_return(false)
        post :create, {:credited_order => {}}, valid_session
        assigns(:credited_order).should be_a_new(CreditedOrder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CreditedOrder.any_instance.stub(:save).and_return(false)
        post :create, {:credited_order => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested credited_order" do
        credited_order = CreditedOrder.create! valid_attributes
        # Assuming there are no other credited_orders in the database, this
        # specifies that the CreditedOrder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CreditedOrder.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => credited_order.to_param, :credited_order => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested credited_order as @credited_order" do
        credited_order = CreditedOrder.create! valid_attributes
        put :update, {:id => credited_order.to_param, :credited_order => valid_attributes}, valid_session
        assigns(:credited_order).should eq(credited_order)
      end

      it "redirects to the credited_order" do
        credited_order = CreditedOrder.create! valid_attributes
        put :update, {:id => credited_order.to_param, :credited_order => valid_attributes}, valid_session
        response.should redirect_to(credited_order)
      end
    end

    describe "with invalid params" do
      it "assigns the credited_order as @credited_order" do
        credited_order = CreditedOrder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CreditedOrder.any_instance.stub(:save).and_return(false)
        put :update, {:id => credited_order.to_param, :credited_order => {}}, valid_session
        assigns(:credited_order).should eq(credited_order)
      end

      it "re-renders the 'edit' template" do
        credited_order = CreditedOrder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CreditedOrder.any_instance.stub(:save).and_return(false)
        put :update, {:id => credited_order.to_param, :credited_order => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested credited_order" do
      credited_order = CreditedOrder.create! valid_attributes
      expect {
        delete :destroy, {:id => credited_order.to_param}, valid_session
      }.to change(CreditedOrder, :count).by(-1)
    end

    it "redirects to the credited_orders list" do
      credited_order = CreditedOrder.create! valid_attributes
      delete :destroy, {:id => credited_order.to_param}, valid_session
      response.should redirect_to(credited_orders_url)
    end
  end

end
